# ======================================================================== #
#               Mandatory variables - set to fit your environment          #
# ======================================================================== #

variables:
   imageFolderPath: 'images'
   serviceConnection: 'equinorta-ci'
   targetContainerRegistry: 'equinorta'
   fullPathName: '$(imageFolderPath)/$(imageName)'
   # Set the 'imageName' variable to the same name as the folder of this file.
   imageName: 'dotnet-3.0-sdk-node-10'  

trigger:
  branches:
    include:
      - azure-pipelines  
  paths:
    include:
      - '$(fullPathName)/*'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: $(serviceConnection) 
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: $(targetContainerRegistry)/$(imageName)
    dockerFile: '$(fullPathName)/Dockerfile'   
    tags: |
      latest